name: Update Rugby Menu

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run rugby automation script
        run: python rugby_automation.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto-update rugby schedule" || echo "No changes to commit"

      - name: Pull latest changes (rebase)
        run: |
          git pull origin main --rebase || echo "Nothing to rebase"

      - name: Push changes
        run: |
          git push origin main || echo "Nothing to push"
