name: Update Rugby Menu

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run rugby automation script
        run: python rugby_automation.py

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull origin main --rebase
          git add -A
          git diff --cached --quiet || git commit -m "Auto-update rugby menu"
          git push origin main
